100-hours-a-week/7-team-ddb-tf-gcp

- modules/nat_bastion/main.tf
- modules/nat_bastion/outputs.tf
- modules/nat_bastion/script/startup.sh
- modules/nat_bastion/variables.tf
private subnet에 인터넷 연결 및 외부 접근위한 nat 겸 bastion module을 작성한다.
- nat_bastion module 파일 생성
- nat 설정 script 작성
- nat_bastion module 작성
- ssh key는 secret manager에 업로드
#18
> Feat: nat&bastion module 작성

- modules/be/main.tf
- modules/be/outputs.tf
- modules/be/scripts/startup.sh
- modules/be/variables.tf
backend module 작성
- be module 생성
- be startup script 작성 (java 17)
- be module 작성
- ssh key는 secret manager에 업로드
#30
- 환경변수는 추후 적용
> Feat: be module 작성

- modules/fe/main.tf
- modules/fe/outputs.tf
- modules/fe/scripts/startup.sh
- modules/fe/variables.tf
FE(Next.js) 프론트엔드 인스턴스를 위한 Terraform 리소스를 추가합니다.
SSH 보안을 위한 키 페어 생성, Secret Manager 저장, Load Balancer 및 Bastion과의 통신을 위한 방화벽 설정을 포함합니다.
- SSH 키 페어 생성 및 Secret Manager 등록
- FE 인스턴스 리소스 구성
- 방화벽 설정
- 인스턴스 그룹 및 헬스체크
Close #22
> Feat: FE module 추가

- modules/ai/main.tf
- modules/ai/outputs.tf
- modules/ai/scripts/startup.sh
- modules/ai/variables.tf
AI(FastAPI) 백엔드 인스턴스 구성을 위한 Terraform 리소스를 추가합니다.
SSH 보안을 위해 키 페어를 생성하고, Secret Manager를 통해 비공개 키를 안전하게 관리하며, Load Balancer 및 Bastion과의 통신을 위한 방화벽 규칙도 포함됩니다.
- SSH 키 페어 생성 및 Secret Manager 등록
- AI 인스턴스 생성 및 설정
- 방화벽 설정
- 인스턴스 그룹 및 헬스체크
Close #34
> Feat: AI module 추가

- envs/static/main.tf
- envs/static/modules/tf_automation/main.tf
- envs/static/modules/tf_automation/variables.tf
- envs/static/variables.tf
기존에 동작하던 terraform 자동화에 db 백업 및 복원을 추가한다.
- database 백업 및 복원 기능 추가
- cloud storage에 이름에 백업 시간 추가 후 저장
- 복원 시 정렬 후 가장 최근 백업한 파일로 복원
#63
> Feat: terraform 자동화 db 백업 추가

- modules/cloud_storage/main.tf
CDN 접근 권한 문제 해결
- 접근성 확보를 위해 allUsers에게 objectViewer 권한을 부여함
Closes #60
> Chore: GCS 버킷을 allUsers에 공개

- envs/dev/main.tf
- envs/prod/main.tf
- modules/cloud_sql/main.tf
- modules/cloud_sql/variables.tf
vpc peering으로 인한 에러를 수정 및 cloud sql 연결점 추가
- vpc peering 제거
- cloud sql public ip 할당
- 연결 가능 범위에 nat ip 주소 추가 
#74
> Hotfix: vpc peering 제거 및 cloud sql에 nat 접근 추가

- envs/static/modules/tf_automation/main.tf
- envs/static/modules/tf_automation/variables.tf
- envs/static/variables.tf
기존 동작하던 terraform 자동화에 cloud storage 백업 및 복원을 자동화한다.
- storage 백업 및 복원 추가
- destroy 자동화 활성화
#64
> Feat: 기존 terraform 자동화에 storage 백업 및 복원 추가

- envs/dev/main.tf
- envs/dev/variables.tf
- envs/prod/main.tf
- envs/prod/variables.tf
- modules/cloud_sql/main.tf
- modules/cloud_sql/variables.tf
db 비밀번호 고정값 제거 및 랜덤 값 지정
- db password를 고정 값이 아닌 random 값을 생성하도록 지정
#82
> Fix: db 비밀번호 고정값 제거 및 랜덤 값 지정

- envs/static/main.tf
- envs/static/modules/tf_automation/main.tf
- envs/static/modules/tf_automation/variables.tf
- envs/static/variables.tf
- postgres db 삭제 전 접속 중인 세션 모두 삭제 및 연결 종료
-
#85
> Fix: terraform 자동화 중 destroy 에러 수정

- envs/dev/.terraform.lock.hcl
- envs/dev/main.tf
- envs/dev/variables.tf
- envs/prod/main.tf
- envs/prod/variables.tf
shared vpc, dev vpc, prod vpc 분리에 따른 dev와 prod를 수정하였습니다. 
- shared <-> dev, shared <-> prod 양방향 통신
- nat gateway, gar을 추가
Closes #89
> Feat: shared vpc 추가에 따른 dev, prod 수정

- envs/prod/.terraform.lock.hcl
- envs/prod/main.tf
- cloudsql 모듈 module.nat_bastion.nat_ip -> module.nat_gateway.nat_ip
#93
> Fix: prod 환경 nat ip 에러 수정

- envs/shared/modules/jenkins/main.tf
- envs/shared/modules/jenkins/scripts/startup.sh
- modules/ai/main.tf
- modules/be/main.tf
- modules/fe/main.tf
Jenkins 인스턴스 생성 후 백업해놓은 데이터를 다운받아 복원할 수 있게 스크립트를 수정하였습니다.
- 복원이 완료될 때까지 Lock을 걸어놓아 새로운 SSH 키를 잃어버리지 않도록 함
- Jenkins 서비스 계정에 백업 버킷에 대한 ObjectAdmin 권한 부여
Closes #92
> Feat: Jenkins 데이터 복원

- envs/shared/main.tf
- envs/shared/modules/jenkins/main.tf
- envs/shared/modules/jenkins/outputs.tf
- envs/shared/modules/jenkins/variables.tf
- envs/shared/variables.tf
Jenkins에 Google HTTPS Load Balancer를 연결했습니다.
- LoadBalancer 연결
Closes #95
> Feat: Jenkins HTTPS Load Balnacer 연결

- envs/static/modules/tf_automation/main.tf
shared 환경을 terraform 자동화에 추가한다.
- shared 환경 apply는 항상 실행
- destroy의 경우 각 환경에 가서 활성화된 list가 없을 경우에만 실행
- 작업 환경, dev, prod 각각 branch clonde 받아서 분리 사용
- 최종 시간 30분으로 증가
#96
> Feat:  shared 환경 terraform 자동화 적용

- envs/shared/main.tf
- envs/shared/modules/jenkins/main.tf
- envs/shared/modules/jenkins/variables.tf
- envs/shared/modules/monitoring/outputs.tf
- source <-> target을 반대로 수정 
- #113
> Fix: jenkins 모니터링 방화벽 수정

- envs/shared/modules/monitoring/files/prometheus.yml
- modules/ai/files/docker-compose.yml
- modules/ai/files/promtail.yml
- modules/ai/main.tf
- modules/ai/scripts/startup.sh
ai module에 promatil을 설치해 로그를 수집하고 fast api와 매트릭을 연결하여 fast api apm을 관측한다.
- ai module promtail 설치
- loki 연결
- apm 연결
- #112
>  feat: fast api 로그 및 apm 연결

- envs/shared/modules/monitoring/files/docker-compose.yml
- envs/shared/modules/monitoring/files/endpoints.yml
- envs/shared/modules/monitoring/files/loki.yml
- envs/shared/modules/monitoring/files/prometheus.yml
- envs/shared/modules/monitoring/files/thanos-gcs.yml
- envs/shared/modules/monitoring/locals.tf
- envs/shared/modules/monitoring/main.tf
- envs/shared/modules/monitoring/scripts/startup.sh
- envs/static/modules/tf_automation/main.tf
모니터링 데이터 ( prometheus, loki)를 백업 및 쿼리 한다.
- 30분에 한번씩 prometheus 데이터 업로드
- 5분에 한번씩 loki 데이터 업로드
- thanos 0.38.0 버전 사용
- thanos sidecar, query, store 전부 docker compose로 관리
- host에 바인드된 볼륨 docker managed volume으로 변경
- stratup.sh에 반영
- #117
> Feat: 모니터링 데이터 백업 

- envs/dev/main.tf
- envs/prod/main.tf
- modules/cloud_sql/data.tf
- modules/cloud_sql/main.tf
cloudsql 사용시 에러가 발생하는 문제 해결
- cloudsql 참조시 버전 적용 및 base64 디코딩 해제
- 각 envs(dev, prod)에서 cloudsql 모듈 project_id 값 추가
- #117
> Fix: cloud sql 비밀번호 설정 수정

- envs/dev/.terraform.lock.hcl
- envs/dev/main.tf
- envs/prod/.terraform.lock.hcl
- envs/prod/main.tf
- envs/static/modules/tf_automation/main.tf
종종 tf 자동화가 정상적으로 수행되지 않는 버그를 수정한다.
-tf 자동화 버그 수정
- vpc peering 생성 오류 수정
#144
> Fix: tf 자동화 버그 수정

- envs/static/main.tf
- envs/static/variables.tf
- static 환경의 projectId, backend, credential 변경
#147
> Chore: GCP 프로젝트 (static 환경) 변경

- envs/shared/modules/jenkins/main.tf
Jenkins에서 GCS에 저장되어 있는 모델을 다운로드하기 위한 서비스 계정 키를 Secret Manager에 저장하는 기능을 추가하였습니다. 
- Jenkins 서비스 계정 키를 Secret Manager에 저장하여 GCS 인증에 활용 가능하도록 개선
Closes #150
> Feat: Jenkins 서비스 계정 키를 Secret Manager에 등록
